version: '3.6'

services:
  influxdb:
    image: influxdb:1.7.1
    container_name: influxdb
    environment:
      INFLUXDB_DATA_INDEX_VERSION: "tsi1"
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    volumes:
      - influxdb-volume:/var/lib/influxdb

  #nginx:
  #  image: nginx:latest
  #  restart: always
  #  container_name: nginx
  #  network_mode: host
  #  ports:
  #    - "9090:9090"
  #  volumes:
  #    - ./nginx.conf:/etc/nginx/nginx.conf:z

  grafana:
    image: grafana/grafana:8.4.6
    restart: always
    container_name: grafana
    ports:
      - "0.0.0.0:8080:3000"
    environment:
      - GF_SMTP_ENABLED=false
    env_file:
      - 'grafana/env'
    depends_on:
      - influxdb

  grafana-sidecar:
    build: grafana
    restart: always
    container_name: grafana-sidecar
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD:-admin}
    depends_on:
      - grafana
    volumes:
      - grafana-volume:/var/lib/grafana

  telegraf:
    build: telegraf
    restart: always
    container_name: telegraf
    hostname: telegraf.rrcockpit
    env_file:
      - 'telegraf/env'
    depends_on:
      - influxdb
    volumes:
      - telegraf-volume:/tmp/telegraf

volumes:
  mariadb-volume:
  influxdb-volume:
    external: true
  grafana-volume:
    external: true
  telegraf-volume:
    external: true
