apiVersion: v1
data:
  DATABASE: telegraf
  HOST_NAME: telegraf
  INFLUXDB_HOST: influxdb
  INFLUXDB_PORT: "8086"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: telegraf-telegraf-env
  name: telegraf-env
