{
 "title": "OADP Periodic - 1.1",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "influxdb_filter", "label": "filter" }
  ]
 },
 "panels": [
  {
   "title": "OADP CI Monitor",
   "type": "text",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# OADP Periodic CI Dashboard - 1.0 ( STILL WIP, validating data)\n\n## Useful links\n* Search for errors:  https://search.ci.openshift.org/  \n* Test Grid: https://testgrid.k8s.io/redhat\n* OADP CI Config: https://github.com/openshift/release/tree/master/ci-operator/config/openshift/oadp-operator\n      \n## builds\n* upstream: https://app.travis-ci.com/github/openshift/oadp-operator\n* downstream: https://jenkins-cpaas-oadp.apps.cpaas-poc.r6c9.p1.openshiftapps.com/\n* internal cvp: https://jenkins-cvp-5d6ccd93bed8bd3809ddcb5d.apps.ocp-c1.prod.psi.redhat.com/view/Production%20Pipeline/job/cvp-product-test/\n\n## Legend\n* success: all oadp tests pass\n* failure: oadp tests failed OR infra failed\n* aborted: the job was canceled ( new patch submitted )\n* flake: the job failed but failed in a way that is UNRELATED to OADP."
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Periodic OADP Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenShift 4.11 Pass / Fail",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*-e2e.*/   AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*-e2e.*/   AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.11.*-e2e.*/   AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*-e2e.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.10 Pass / Fail",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*-e2e.*/   AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*-e2e.*/   AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.10.*-e2e.*/   AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*-e2e.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.9 Pass / Fail",
     "type": "piechart",
     "gridPos": { "h": 11, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*-e2e.*/   AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.9.*-e2e.*/   AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.9.*-e2e.*/   AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.9.*-e2e.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Periodic OADP Details by Version",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "OpenShift 4.11 AWS",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.11.*aws.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*aws.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*aws.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*aws.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.11 GCP",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.11.*gcp.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*gcp.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*gcp.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*gcp.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.11 Azure",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.11.*azure.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*azure.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.11.*azure.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.11.*azure.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.11 AWS Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 22 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.11.*aws.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.11 GCP Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 28 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.11.*gcp.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.11 Azure Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.11.*azure.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.10 AWS",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.10.*aws.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*aws.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*aws.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*aws.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.10 GCP",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.10.*gcp.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*gcp.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*gcp.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*gcp.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.10 Azure",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.10.*azure.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*azure.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.10.*azure.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.10.*azure.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.10 AWS Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 49 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.10.*aws.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.10 GCP Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.10.*gcp.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.10 Azure Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 61 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.10.*azure.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.9 AWS",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.9.*aws.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*aws.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.9.*aws.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*aws.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.9 GCP",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.9.*gcp.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*gcp.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.9.*gcp.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*gcp.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OpenShift 4.9 Azure",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "alias": "SUCCESS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~    /^periodic.*1.1.*4.9.*azure.*/  AND \"state\" = 'success' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FAILURE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*azure.*/  AND \"state\" = 'failure' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "ABORTED",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~  /^periodic.*1.1.*4.9.*azure.*/  AND \"state\" = 'aborted' ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "FLAKE",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT count(\"state\") FROM \"build\"  WHERE (\"job_name\" =~   /^periodic.*1.1.*4.9.*azure.*/  AND \"state\" = 'flake' ) AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.9 AWS Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.9.*aws.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.9 GCP Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 82 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.9.*gcp.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "OADP -  OpenShift 4.9 Azure Periodic",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 88 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT \"job_name\", \"state_int\", \"build_id\", \"end_time\", \"duration\", \"log\" FROM \"build\"  WHERE (\"job_name\" =~ /^periodic.*1.1.*4.9.*azure.*/  ) AND $timeFilter ",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}