apiVersion: v1
data:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-clock-panel,grafana-googlesheets-datasource,snuids-trafficlights-panel
  GF_USERS_ALLOW_ORG_CREATE: "false"
  GF_USERS_ALLOW_SIGN_UP: "false"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-grafana-env
  name: grafana-env
