apiVersion: v1
kind: List
items:
  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: grafana
      namespace: go-scrape-prow
    spec:
      path: /
      to:
        kind: Service
        name: grafana
      port:
        targetPort: front