kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: telegraff
  namespace: go-scrape-prow
  labels:
    app: telegraf
    app.kubernetes.io/component: telegraf
    app.kubernetes.io/instance: telegraf
    app.kubernetes.io/name: telegraf
    app.kubernetes.io/part-of: go-scrape-prow
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'telegraf:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/hhpatel14/go_scrape_prow.git'
      ref: newOpenshift
    contextDir: /telegraf
    sourceSecret:
      name: openshift
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: telegraf-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: telegraf-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
