## Build images using dockerfiles in /telegraf and /grafana 
## prerequisite: Please follow document to create Source Secret and Webhook Secret 

apiVersion: v1
kind: List
items:
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: telegraf
      namespace: go-scrape-prow
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      name: grafana-sidecar
      namespace: go-scrape-prow
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: grafana-sidecar
      namespace: go-scrape-prow
      labels:
        app: grafana-sidecar
        app.kubernetes.io/component: grafana-sidecar
        app.kubernetes.io/instance: grafana-sidecar
        app.kubernetes.io/name: grafana-sidecar
        app.kubernetes.io/part-of: go-scrape-prow
    spec:
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: 'grafana-sidecar:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      source:
        type: Git
        git:
          uri: 'https://github.com/hhpatel14/go_scrape_prow.git'
          ref: main
        contextDir: /grafana
      runPolicy: Serial
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: telegraf
      namespace: go-scrape-prow
      labels:
        app: telegraf
        app.kubernetes.io/component: telegraf
        app.kubernetes.io/instance: telegraf
        app.kubernetes.io/name: telegraf
        app.kubernetes.io/part-of: go-scrape-prow
    spec:
      output:
        to:
          kind: ImageStreamTag
          name: 'telegraf:latest'
      resources: {}
      successfulBuildsHistoryLimit: 5
      failedBuildsHistoryLimit: 5
      strategy:
        type: Docker
        dockerStrategy:
          dockerfilePath: Dockerfile
      postCommit: {}
      source:
        type: Git
        git:
          uri: 'https://github.com/hhpatel14/go_scrape_prow.git'
          ref: main
        contextDir: /telegraf
      runPolicy: Serial
